apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserverinfo
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      app: webapp
    spec:
      containers:
      - name: webapp
        image: ajju13/pyserverinfo:28
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: pyserverinfo-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30231
  selector:
      app: webapp
