apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyserverinfo
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels: 
        app: webapp
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: webapp
          image: ajju13/pyserverinfo-service:32
          ports:
            - containerPort: 3000